#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
# 
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#


name: Custom EFI
on:
  workflow_dispatch:
    inputs:
      ocver:
        description: 'rel | pre | mod'
        required: true
        default: 'mod' 
        type: choice
        options:
        - rel
        - pre
        - mod

      itlwm:
        description: 'ventura | monterey | big_sur'
        required: true
        default: 'ventura' 
        type: choice
        options:
        - ventura
        - monterey
        - big_sur

      kexts:
        description: 'stable | alpha'
        required: true
        default: 'alpha' 
        type: choice
        options:
        - stable
        - alpha

env:
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
  ACID32: 1


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run : |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo systemsetup -settimezone "Asia/Shanghai"

      - name: Install Python Dependencies
        run: |
          python3 -m pip install -U pip
          pip3 install datetime urllib3 wget

      - name: Run Updater
        run: |
          echo "OCVer: ${{ inputs.ocver }}" > custom.txt
          echo "itlwm: ${{ inputs.itlwm }}" >> custom.txt
          echo "kexts: ${{ inputs.kexts }}" >> custom.txt

          echo "tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV

          python3 -u update.py -o ${{ inputs.ocver }} -i ${{ inputs.itlwm }} -k ${{ inputs.kexts }} -t ${{ secrets.GITHUB_TOKEN }}

      - name: Zip EFI Ventura
        uses: vimtor/action-zip@v1
        with:
          files: EFI README.md custom.txt
          recursive: false
          dest: ${{ steps.tag.outputs.repository_name }}-Custom-${{ env.status }}.zip

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Custom EFI
          path: Hackintosh*.zip
