name: tests
on:
  push:
  workflow_dispatch:

env:
  # rel, pre, mod
  ocver: pre

jobs:
  test-and-cover:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main

      #- uses: brokeyourbike/ocvalidate-action@v0.2
      #  with:
      #    opencore-version: '0.8.6'
      #    release: true
      #
      #- run: |
      #    ocvalidate "EFI/OC/config.plist" || exit 1
      #    ocvalidate "EFI/OC/config_iGPU.plist" || exit 1
      #    ocvalidate "EFI/OC/config_RX5700XT.plist" || exit 1
      #    ocvalidate "EFI/OC/config_RX5700XT&iGPU.plist" || exit 1

      - name: Get OC-Mod
        run: |
          brew install curl jq

          if [ ${ocver} == 'rel' ]; then
            url="https://api.github.com/repos/acidanthera/OpenCorePkg/releases"
          elif [ ${ocver} == 'pre' ]; then
            url="https://api.github.com/repos/dortania/build-repo/releases"
          else
            url="https://api.github.com/repos/wjz304/OpenCore_NO_ACPI_Build/releases"
          fi

          ocdownloadurl=$(curl -L ${url} | jq -r .assets[1].browser_download_url)
          curl -L ${ocdownloadurl} -o oc.zip
          unzip oc.zip -d oc

      - run: |
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config.plist" || exit 1
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config_iGPU.plist" || exit 1
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config_RX5700XT.plist" || exit 1
          oc/Utilities/ocvalidate/ocvalidate "EFI/OC/config_RX5700XT&iGPU.plist" || exit 1